#!/bin/bash

# Simplified setup for SkillForge Local Devnet
# Uses pre-configured genesis instead of generating from scratch
set -e

echo "🚀 Setting up SkillForge Local Devnet (Simplified)..."

# Check prerequisites
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Please install Docker first."
    exit 1
fi

# Create directories
mkdir -p configs keys genesis data/node-1 data/node-2 data/node-3 data/kupo

# Generate keys if they don't exist
if [ ! -f keys/payment.skey ]; then
    echo "🔑 Generating payment and stake keys..."
    
    if ! command -v cardano-cli &> /dev/null; then
        echo "⚠️  cardano-cli not found. Using placeholder keys."
        echo "placeholder-payment-key" > keys/payment.skey
        echo "placeholder-payment-vkey" > keys/payment.vkey
        echo "placeholder-stake-key" > keys/stake.skey
        echo "placeholder-stake-vkey" > keys/stake.vkey
        echo "addr_test1placeholder" > keys/payment.addr
    else
        cardano-cli address key-gen \
            --verification-key-file keys/payment.vkey \
            --signing-key-file keys/payment.skey

        cardano-cli stake-address key-gen \
            --verification-key-file keys/stake.vkey \
            --signing-key-file keys/stake.skey

        # Build payment address
        cardano-cli address build \
            --payment-verification-key-file keys/payment.vkey \
            --stake-verification-key-file keys/stake.vkey \
            --testnet-magic 42 \
            --out-file keys/payment.addr
    fi
fi

PAYMENT_ADDR=$(cat keys/payment.addr)
echo "✓ Payment address: $PAYMENT_ADDR"

# Create minimal node configuration
echo "⚙️ Creating node configuration..."

cat > configs/node-config.json <<EOF
{
  "AlonzoGenesisFile": "genesis/alonzo-genesis.json",
  "AlonzoGenesisHash": "local-alonzo-hash",
  "ByronGenesisFile": "genesis/byron-genesis.json",
  "ByronGenesisHash": "local-byron-hash",
  "ShelleyGenesisFile": "genesis/shelley-genesis.json",
  "ShelleyGenesisHash": "local-shelley-hash",
  "ConwayGenesisFile": "genesis/conway-genesis.json",
  "ConwayGenesisHash": "local-conway-hash",
  "RequiresNetworkMagic": "RequiresMagic",
  "TestShelleyHardForkAtEpoch": 0,
  "TestAllegraHardForkAtEpoch": 0,
  "TestMaryHardForkAtEpoch": 0,
  "TestAlonzoHardForkAtEpoch": 0,
  "TestBabbageHardForkAtEpoch": 0,
  "TestConwayHardForkAtEpoch": 0,
  "LastKnownBlockVersion-Major": 8,
  "LastKnownBlockVersion-Minor": 0,
  "LastKnownBlockVersion-Alt": 0,
  "Protocol": "Cardano",
  "TraceBlockFetchDecisions": false,
  "TraceBlockchainTime": false,
  "TraceChainDb": false,
  "TraceChainSync": false,
  "TraceChainSyncBlockServer": false,
  "TraceChainSyncClient": false,
  "TraceChainSyncHeaderServer": false,
  "TraceChainSyncProtocol": false,
  "TraceConnectionManager": false,
  "TraceDNSResolver": false,
  "TraceDNSSubscription": false,
  "TraceErrorPolicy": false,
  "TraceForge": false,
  "TraceHandshake": false,
  "TraceInboundGovernor": false,
  "TraceIpSubscription": false,
  "TraceLedgerPeers": false,
  "TraceLocalChainSync": false,
  "TraceLocalErrorPolicy": false,
  "TraceLocalHandshake": false,
  "TraceLocalRootPeers": false,
  "TraceLocalTxSubmission": false,
  "TraceLocalTxSubmissionServer": false,
  "TraceMux": false,
  "TracePeerSelection": false,
  "TracePeerSelectionActions": false,
  "TracePublicRootPeers": false,
  "TraceServer": false,
  "TraceSubscription": false,
  "TraceTxInbound": false,
  "TraceTxOutbound": false,
  "TraceTxSubmission": false,
  "TracingVerbosity": "NormalVerbosity",
  "TurnOnLogging": true,
  "defaultScribes": [["StdoutSK", "stdout"]],
  "setupScribes": [{
    "scKind": "StdoutSK",
    "scName": "stdout",
    "scFormat": "ScText",
    "scRotation": null
  }],
  "minSeverity": "Info"
}
EOF

# Create topology
cat > configs/topology.json <<EOF
{
  "Producers": [
    {
      "addr": "cardano-node-1",
      "port": 3001,
      "valency": 1
    },
    {
      "addr": "cardano-node-2",
      "port": 3002,
      "valency": 1
    },
    {
      "addr": "cardano-node-3",
      "port": 3003,
      "valency": 1
    }
  ]
}
EOF

# Create placeholder genesis files (will be generated by cardano-node in Docker)
mkdir -p genesis
echo "{}" > genesis/alonzo-genesis.json
echo "{}" > genesis/byron-genesis.json
echo "{}" > genesis/shelley-genesis.json
echo "{}" > genesis/conway-genesis.json

echo "✅ Devnet configuration created"
echo ""
echo "📝 Next steps:"
echo "   1. Start nodes: docker-compose up -d"
echo "   2. Wait for nodes to sync (check: docker-compose logs cardano-node-1)"
echo "   3. Fund address: ./faucet.sh $PAYMENT_ADDR"
echo "   4. Query UTXOs: ./query-utxo.sh $PAYMENT_ADDR"
echo ""
echo "💡 Payment address: $PAYMENT_ADDR"
echo "💡 Note: Genesis will be auto-generated by cardano-node on first run"



